name: Publish news

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0' # Specify the Ruby version you need for your project
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Run the script
        run: ruby main.rb
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          NEWS_RSS_SOURCES: 'https://www.montevideo.com.uy/anxml.aspx\?58'
          MOOD_THRESHOLD: -0.55
          EXCLUDED_CATEGORIES: 'Policiales'
          PERIODICITY: ${{ vars.PERIODICITY }}
          DEBUG: ${{ vars.DEBUG }}
